#!/usr/bin/python

import os
import ConfigParser
import sys
import re

# read the file descriptor first

descFile = "./descriptor.conf"
if not os.path.isfile(descFile):
	print '\nERR: descriptor %s does not exist!\n' % (configFile)
	sys.exit()
descriptor = ConfigParser.ConfigParser()
descriptor.read(descFile)

lb = 0
fw = 0

for each_section in descriptor.sections():
	if re.search('FW', each_section):
		lb=lb+1
		print lb

# iterate through sections
for each_section in descriptor.sections():
	if re.search ('FW', each_section):
		for (each_key, each_val_lb) in descriptor.items(each_section):
			if each_key == 'ip':
				print each_val_lb

				# define lb.conf
				lb_conf = "ansible/roles/uploadscript/files/web_lb/baru1.conf"
				if not os.path.isfile(lb_conf):
					lbcfg = open(lb_conf, 'w')

					# copy values
					print lb	
					Config = ConfigParser.ConfigParser()
					Config.add_section('LoadBalancer')
					Config.set('LoadBalancer', 'fanout', lb)
					for i in range(0,lb):
						Config.set('LoadBalancer', 'fanout_ip_'+str(i+1), each_val_lb)
					Config.write(lbcfg)
					lbcfg.close()

	elif re.search('DB', each_section):
		fw=fw+1
		for (each_key, each_val_fw) in descriptor.items(each_section):
			if each_key == 'ip':
				print each_val_fw

				# define fw.conf
				fw_conf = "ansible/roles/uploadscript/files/web_forward/fw.conf"
				if not os.path.isfile(fw_conf):
					fwcfg = open(fw_conf, 'w')
                                	# copy values
	
					Config = ConfigParser.ConfigParser()
					Config.add_section('Forwarder')
					Config.set('Forwarder', 'target', fw)
					for i in range(0,fw):
						Config.set('Forwarder', 'target_ip_'+str(i+1), each_val_fw)
					Config.write(fwcfg)
					fwcfg.close()


