---
# tasks file for bootvm1
- name: get list VMs
  virt:
          command: list_vms
  register: output_vms

- debug:
        msg: "Existing VMs: {{ output_vms.list_vms }}"

- name: run all the VMs
  virt:
          name: "{{ item }}"
          #          state: running
          state: shutdown
  with_list: "{{ output_vms.list_vms }}"

- name: wait for VM to become available
  wait_for:
          timeout: 300
  delegate_to: localhost


