---

- name: manage libvirt guests
  hosts: 127.0.0.1
  connection: local 

  tasks: 
#    - name: start libvirtd
#      service:
#        name: libvirtd
#        state: started
#        enabled: yes

    - name: get list VMs
      virt:
        command: list_vms 
      register: output_vms

#    - debug:
#        msg: "{{ output_vms.list_vms }}"

    - name: run all the VMs
      virt:
        name: "{{ output_vms.list_vms[1] }}" 
        state: running 

    - name: check VM status
      virt:
        name: "{{ output_vms.list_vms[1] }}"
        command: status
      register: output_status
 
    - debug:
        msg: "{{ output_status }}"
